import type { Metadata } from "next";
import { Geist, Geist_Mono, Italianno } from "next/font/google";
import ConditionalHeader from "@/components/layout/conditional-header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const italianno = Italianno({
  variable: "--font-italianno",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Virkadevasen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} ${italianno.variable}`}
    >
      <body>
        <ConditionalHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
